{% set version = "0.23-4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ttr
  version: {{ version|replace("-", "_") }}

source:
  fn: TTR_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/TTR_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/TTR/TTR_{{ version }}.tar.gz
  sha256: eb17604da986213b3b924f0af65c3d089502a658a253ee34f6b8f6caccf6bfa2

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-xts >=0.9_3
    - r-zoo

  run:
    - r-base
    - r-xts >=0.9_3
    - r-zoo

test:
  commands:
    - $R -e "library('TTR')"  # [not win]
    - "\"%R%\" -e \"library('TTR')\""  # [win]

about:
  home: https://github.com/joshuaulrich/TTR
  license: GPL-2
  summary: Functions and data to construct technical trading rules with R.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
