{% set version = '0.23-4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ttr
  version: {{ version|replace("-", "_") }}

source:
  fn: TTR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/TTR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/TTR/TTR_{{ version }}.tar.gz
  sha256: eb17604da986213b3b924f0af65c3d089502a658a253ee34f6b8f6caccf6bfa2

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-curl
    - r-xts >=0.10_0
    - r-zoo
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-curl
    - r-xts >=0.10_0
    - r-zoo

test:
  commands:
    - $R -e "library('TTR')"           # [not win]
    - "\"%R%\" -e \"library('TTR')\""  # [win]

about:
  home: https://github.com/joshuaulrich/TTR
  license: GPL-2
  summary: Functions and data to construct technical trading rules with R.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
